from PyQt5 import QtCore, QtGui, QtWidgets
import res_rc


class Ui_home(object):
    def setupUi(self, home):
        home.setObjectName("home")
        home.resize(827, 518)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/home/personal.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        home.setWindowIcon(icon)
        home.setLayoutDirection(QtCore.Qt.RightToLeft)
        home.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.centralwidget = QtWidgets.QWidget(home)
        self.centralwidget.setObjectName("centralwidget")
        self.namelbl = QtWidgets.QLabel(self.centralwidget)
        self.namelbl.setGeometry(QtCore.QRect(733, 13, 40, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.namelbl.sizePolicy().hasHeightForWidth())
        self.namelbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("IRNazanin")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.namelbl.setFont(font)
        self.namelbl.setObjectName("namelbl")
        self.cpybtn = QtWidgets.QPushButton(self.centralwidget)
        self.cpybtn.setGeometry(QtCore.QRect(470, 280, 130, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpybtn.sizePolicy().hasHeightForWidth())
        self.cpybtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("IRNazanin")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cpybtn.setFont(font)
        self.cpybtn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                  "border-color: rgb(255, 255, 255);\n"
                                  "color: rgb(255, 255, 255);")
        self.cpybtn.setObjectName("cpybtn")
        self.deletebtn = QtWidgets.QPushButton(self.centralwidget)
        self.deletebtn.setGeometry(QtCore.QRect(470, 213, 130, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deletebtn.sizePolicy().hasHeightForWidth())
        self.deletebtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("IRNazanin")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.deletebtn.setFont(font)
        self.deletebtn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                     "border-color: rgb(255, 255, 255);\n"
                                     "color: rgb(255, 255, 255);")
        self.deletebtn.setObjectName("deletebtn")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(4, 13, 441, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.lenval = QtWidgets.QLineEdit(self.centralwidget)
        self.lenval.setGeometry(QtCore.QRect(466, 113, 270, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lenval.sizePolicy().hasHeightForWidth())
        self.lenval.setSizePolicy(sizePolicy)
        self.lenval.setObjectName("lenval")
        self.searchbtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchbtn.setGeometry(QtCore.QRect(610, 280, 130, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchbtn.sizePolicy().hasHeightForWidth())
        self.searchbtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("IRNazanin")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.searchbtn.setFont(font)
        self.searchbtn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                     "border-color: rgb(255, 255, 255);\n"
                                     "color: rgb(255, 255, 255);")
        self.searchbtn.setObjectName("searchbtn")
        self.closeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.closeBtn.setGeometry(QtCore.QRect(470, 403, 270, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeBtn.sizePolicy().hasHeightForWidth())
        self.closeBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("IRNazanin")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.closeBtn.setFont(font)
        self.closeBtn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                    "border-color: rgb(255, 255, 255);\n"
                                    "color: rgb(255, 255, 255);")
        self.closeBtn.setObjectName("closeBtn")
        self.next_pagebtn = QtWidgets.QPushButton(self.centralwidget)
        self.next_pagebtn.setGeometry(QtCore.QRect(236, 430, 210, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_pagebtn.sizePolicy().hasHeightForWidth())
        self.next_pagebtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.next_pagebtn.setFont(font)
        self.next_pagebtn.setToolTip("")
        self.next_pagebtn.setToolTipDuration(2)
        self.next_pagebtn.setWhatsThis("")
        self.next_pagebtn.setObjectName("next_pagebtn")
        self.savebtn = QtWidgets.QPushButton(self.centralwidget)
        self.savebtn.setGeometry(QtCore.QRect(470, 343, 270, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savebtn.sizePolicy().hasHeightForWidth())
        self.savebtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("IRNazanin")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.savebtn.setFont(font)
        self.savebtn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                   "border-color: rgb(255, 255, 255);\n"
                                   "color: rgb(255, 255, 255);")
        self.savebtn.setObjectName("savebtn")
        self.userNameLbl = QtWidgets.QLabel(self.centralwidget)
        self.userNameLbl.setGeometry(QtCore.QRect(747, 63, 71, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userNameLbl.sizePolicy().hasHeightForWidth())
        self.userNameLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("IRNazanin")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.userNameLbl.setFont(font)
        self.userNameLbl.setObjectName("userNameLbl")
        self.userNameVal = QtWidgets.QLineEdit(self.centralwidget)
        self.userNameVal.setGeometry(QtCore.QRect(466, 63, 270, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userNameVal.sizePolicy().hasHeightForWidth())
        self.userNameVal.setSizePolicy(sizePolicy)
        self.userNameVal.setObjectName("userNameVal")
        self.lenlbl = QtWidgets.QLabel(self.centralwidget)
        self.lenlbl.setGeometry(QtCore.QRect(740, 113, 81, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lenlbl.sizePolicy().hasHeightForWidth())
        self.lenlbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("IRNazanin")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lenlbl.setFont(font)
        self.lenlbl.setObjectName("lenlbl")
        self.passlbl = QtWidgets.QLabel(self.centralwidget)
        self.passlbl.setGeometry(QtCore.QRect(741, 163, 51, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passlbl.sizePolicy().hasHeightForWidth())
        self.passlbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("IRNazanin")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.passlbl.setFont(font)
        self.passlbl.setObjectName("passlbl")
        self.generatebtn = QtWidgets.QPushButton(self.centralwidget)
        self.generatebtn.setGeometry(QtCore.QRect(610, 213, 130, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generatebtn.sizePolicy().hasHeightForWidth())
        self.generatebtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("IRNazanin")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.generatebtn.setFont(font)
        self.generatebtn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                       "border-color: rgb(255, 255, 255);\n"
                                       "color: rgb(255, 255, 255);")
        self.generatebtn.setObjectName("generatebtn")
        self.pre_pagebtn = QtWidgets.QPushButton(self.centralwidget)
        self.pre_pagebtn.setGeometry(QtCore.QRect(6, 430, 210, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_pagebtn.sizePolicy().hasHeightForWidth())
        self.pre_pagebtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pre_pagebtn.setFont(font)
        self.pre_pagebtn.setObjectName("pre_pagebtn")
        self.nameval = QtWidgets.QLineEdit(self.centralwidget)
        self.nameval.setGeometry(QtCore.QRect(466, 13, 270, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameval.sizePolicy().hasHeightForWidth())
        self.nameval.setSizePolicy(sizePolicy)
        self.nameval.setObjectName("nameval")
        self.passval = QtWidgets.QLineEdit(self.centralwidget)
        self.passval.setGeometry(QtCore.QRect(466, 163, 270, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passval.sizePolicy().hasHeightForWidth())
        self.passval.setSizePolicy(sizePolicy)
        self.passval.setObjectName("passval")
        home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 26))
        self.menubar.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "background-color: rgb(0, 0, 127);")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        home.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(home)
        self.statusbar.setObjectName("statusbar")
        home.setStatusBar(self.statusbar)
        self.SelectDB = QtWidgets.QAction(home)
        self.SelectDB.setObjectName("SelectDB")
        self.CreateDB = QtWidgets.QAction(home)
        self.CreateDB.setObjectName("CreateDB")
        self.Quit = QtWidgets.QAction(home)
        self.Quit.setObjectName("Quit")
        self.menuFile.addAction(self.SelectDB)
        self.menuFile.addAction(self.CreateDB)
        self.menuFile.addAction(self.Quit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.retranslateUi(home)
        QtCore.QMetaObject.connectSlotsByName(home)
        self.nameval.setClearButtonEnabled(True)
        self.userNameVal.setClearButtonEnabled(True)
        self.lenval.setClearButtonEnabled(True)
        self.passval.setClearButtonEnabled(True)
        QtWidgets.QWidget.setTabOrder(self.nameval, self.userNameVal)
        QtWidgets.QWidget.setTabOrder(self.userNameVal, self.lenval)
        QtWidgets.QWidget.setTabOrder(self.lenval, self.passval)
        QtWidgets.QWidget.setTabOrder(self.passval, self.generatebtn)
        QtWidgets.QWidget.setTabOrder(self.generatebtn, self.deletebtn)
        QtWidgets.QWidget.setTabOrder(self.deletebtn, self.searchbtn)
        QtWidgets.QWidget.setTabOrder(self.searchbtn, self.cpybtn)
        QtWidgets.QWidget.setTabOrder(self.cpybtn, self.savebtn)
        QtWidgets.QWidget.setTabOrder(self.savebtn, self.closeBtn)
        QtWidgets.QWidget.setTabOrder(self.closeBtn, self.pre_pagebtn)
        QtWidgets.QWidget.setTabOrder(self.pre_pagebtn, self.next_pagebtn)
        self.closeBtn.clicked.connect(home.close)
        self.Quit.triggered.connect(home.close)
        home.setWindowFlags(home.windowFlags() & ~QtCore.Qt.WindowMaximizeButtonHint)

    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "مدیریت پسوردها"))
        self.namelbl.setText(_translate("home", "نام:"))
        self.cpybtn.setText(_translate("home", "کپی پسورد"))
        self.deletebtn.setText(_translate("home", "حذف"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("home", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("home", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("home", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("home", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("home", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("home", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("home", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("home", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("home", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("home", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("home", "نام"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("home", "نام کاربری"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("home", "پسورد"))
        self.searchbtn.setText(_translate("home", "جستجو براساس نام"))
        self.closeBtn.setText(_translate("home", "بستن"))
        self.next_pagebtn.setText(_translate("home", ">>"))
        self.savebtn.setText(_translate("home", "ذخیره"))
        self.userNameLbl.setText(_translate("home", "نام کاربری:"))
        self.lenlbl.setText(_translate("home", "طول پسورد:"))
        self.passlbl.setText(_translate("home", "پسورد:"))
        self.generatebtn.setText(_translate("home", "ایجاد پسورد"))
        self.pre_pagebtn.setText(_translate("home", "<<"))
        self.menuFile.setTitle(_translate("home", "فایل"))
        self.SelectDB.setText(_translate("home", "انتخاب دیتابیس"))
        self.CreateDB.setText(_translate("home", "ایجاد دیتابیس جدید"))
        self.Quit.setText(_translate("home", "خروج"))
